spring:
  application:
    name: JournalApp
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://sunnykrr501_db_user:ZzAGV2NU6zdUWr75@cluster0.u2qvbzj.mongodb.net/?appName=Cluster0
      database: journaldb

server:
  port: 8080
#   servlet:
#     context-path: /journal